// Жетістіктер тізімі — бұл ойынның тұрақты контенті (mock емес),
// нақты прогресс деректері achievements_progress кестесінен келеді

export const ACHIEVEMENTS = [
  {
    id: "first-blocks",
    title: "Первые шаги",
    description: "Захватите 10 блоков территории",
    threshold: 10,
    metric: "blocks",
    reward: 2000,
  },
  {
    id: "fifty-blocks",
    title: "Разведчик",
    description: "Захватите 50 блоков территории",
    threshold: 50,
    metric: "blocks",
    reward: 5000,
  },
  {
    id: "hundred-blocks",
    title: "Завоеватель",
    description: "Захватите 100 блоков территории",
    threshold: 100,
    metric: "blocks",
    reward: 10000,
  },
  {
    id: "first-loop",
    title: "Замкнутый круг",
    description: "Завершите первый замкнутый маршрут",
    threshold: 1,
    metric: "loops",
    reward: 1500,
  },
  {
    id: "ten-loops",
    title: "Картограф",
    description: "Завершите 10 замкнутых маршрутов",
    threshold: 10,
    metric: "loops",
    reward: 8000,
  },
  {
    id: "distance-10k",
    title: "Марафонец",
    description: "Пройдите суммарно 10 км",
    threshold: 10,
    metric: "distance_km",
    reward: 3000,
  },
  {
    id: "distance-100k",
    title: "Странник",
    description: "Пройдите суммарно 100 км",
    threshold: 100,
    metric: "distance_km",
    reward: 15000,
  },
  {
    id: "top-10",
    title: "Элита",
    description: "Войдите в топ-10 рейтинга",
    threshold: 10,
    metric: "rank",
    reward: 20000,
  },
  {
    id: "streak-7",
    title: "Постоянство",
    description: "Играйте 7 дней подряд",
    threshold: 7,
    metric: "streak_days",
    reward: 12000,
  },
  {
    id: "top-1",
    title: "Император территорий",
    description: "Займите первое место в рейтинге",
    threshold: 1,
    metric: "rank",
    reward: 50000,
  },
];
