import { createContext, useContext } from 'react';

export const LangContext = createContext(null);
export const useLang = () => useContext(LangContext);

export const translations = {
  RU: {
    langName: 'Русский',
    nav: {
      dashboard: 'Главная',
      donates: 'Донаты',
      faq: 'FAQ',
    },
    hero: {
      eyebrow: 'ОНЛАЙН СЕРВЕР',
      subtitle: 'СЛЕДУЮЩЕЕ ПОКОЛЕНИЕ',
      desc: 'MortyMC — лучший Minecraft сервер в Казахстане. Новый опыт, новые друзья, новые достижения.',
      join: 'Подключиться',
      explore: 'Подробнее',
      ip: 'IP Сервера:',
      copy: 'Скопировать',
    },
    about: {
      eyebrow: 'О НАС',
      title: 'THE MORTYMC',
      desc: 'MortyMC — это не просто игра, это сообщество. На нашем сервере ты найдёшь новых друзей, победишь в эпических битвах и создашь свой мир.',
      btn1: 'Подключиться',
      btn2: 'Донаты',
    },
    gameplay: {
      title: 'СТРАНИЦЫ',
    },
    stats: {
      players: 'Игроков',
      online: 'Онлайн',
      worlds: 'Миров',
      uptime: 'Аптайм',
    },
    donates: {
      title: 'Донаты',
      subtitle: 'Поддержи сервер и получи эксклюзивные привилегии',
      order: 'Заказать',
      backBtn: 'Назад',
      empty: 'Донаты пока не добавлены',
      sending: 'Отправка...',
      modal: {
        title: 'Оформить заказ',
        nick: 'Minecraft ник',
        phone: 'Номер телефона',
        file: 'Чек / квитанция',
        fileBtn: 'Выбрать файл',
        submit: 'Отправить',
        success: 'Заказ принят! Ожидайте подтверждения.',
        error: 'Ошибка, попробуйте снова.',
      },
    },
    faq: {
      title: 'Частые Вопросы',
      subtitle: 'Инструкция по покупке доната',
      backBtn: 'Назад',
      instruction: 'Инструкция',
      step1title: 'Выберите донат',
      step1desc: 'В разделе донатов выберите нужный пакет и переведите деньги на банковскую карту.',
      step2title: 'Отправьте чек',
      step2desc: 'После оплаты нажмите «Заказать», укажите ник, телефон и прикрепите чек.',
      step3title: 'Ожидайте подтверждения',
      step3desc: 'Администратор проверит заказ и активирует донат. Ответ в течение 1-24 часов.',
      requisite: 'Реквизиты банка:',
      faqListTitle: 'Частые вопросы',
      items: [
        {
          q: 'Как подключиться к серверу?',
          a: 'Откройте Minecraft, перейдите в раздел Multiplayer, добавьте сервер с адресом mortymc.altyn.fun и нажмите «Подключиться».',
        },
        {
          q: 'Какая версия Minecraft поддерживается?',
          a: 'Сервер поддерживает Java Edition 1.20+ и Bedrock Edition. Рекомендуется использовать последнюю версию.',
        },
        {
          q: 'Как долго активируется донат?',
          a: 'Донат активируется в течение 1-24 часов после подтверждения администратором.',
        },
        {
          q: 'Могу ли я получить возврат средств?',
          a: 'Возврат средств не предусмотрен после активации доната. В случае технических проблем обратитесь к администрации.',
        },
      ],
    },
    admin: {
      title: 'Вход для администратора',
      placeholder: 'Код доступа',
      submit: 'Войти',
      error: 'Неверный пароль',
      addDonate: '+ Добавить донат',
      donatesTab: 'Донаты',
      viewReceipt: 'Просмотреть чек',
      saved: 'Сохранено',
      orders: 'Заказы',
      editRequisite: 'Реквизиты',
      logout: 'Выйти',
      noOrders: 'Заказов пока нет',
      noDonates: 'Донаты пока не добавлены',
      delete: 'Удалить',
      donateForm: {
        title: 'Новый донат',
        name: 'Название',
        price: 'Цена (₸)',
        desc: 'Описание',
        image: 'Изображение',
        save: 'Сохранить',
        cancel: 'Отмена',
      },
    },
    footer: {
      rights: '© 2026 MortyMC. Все права защищены.',
    },
  },

  KZ: {
    langName: 'Қазақша',
    nav: {
      dashboard: 'Басты бет',
      donates: 'Донаттар',
      faq: 'FAQ',
    },
    hero: {
      eyebrow: 'ОНЛАЙН СЕРВЕР',
      subtitle: 'ЖАҢА БУЫН',
      desc: 'MortyMC — Қазақстандағы үздік Minecraft сервері. Жаңа тәжірибе, жаңа достар, жаңа жетістіктер.',
      join: 'Қосылу',
      explore: 'Толығырақ',
      ip: 'Сервер IP:',
      copy: 'Көшіру',
    },
    about: {
      eyebrow: 'БІЗ ТУРАЛЫ',
      title: 'THE MORTYMC',
      desc: 'MortyMC — бұл жай ғана ойын емес, бұл қауымдастық. Біздің серверде сен жаңа достар табасың, эпикалық шайқастарда жеңіске жетесің және өз әлеміңді жасайсың.',
      btn1: 'Қосылу',
      btn2: 'Донаттар',
    },
    gameplay: {
      title: 'СТРАНИЦЫ',
    },
    stats: {
      players: 'Ойыншылар',
      online: 'Онлайн',
      worlds: 'Әлемдер',
      uptime: 'Жұмыс уақыты',
    },
    donates: {
      title: 'Донаттар',
      subtitle: 'Серверді қолдап, эксклюзивті артықшылықтарға ие бол',
      order: 'Тапсырыс беру',
      backBtn: 'Артқа',
      empty: 'Донаттар әлі қосылмаған',
      sending: 'Жіберілуде...',
      modal: {
        title: 'Тапсырысты рәсімдеу',
        nick: 'Minecraft ник',
        phone: 'Телефон нөірі',
        file: 'Чек / түбіртек',
        fileBtn: 'Файл таңдау',
        submit: 'Жіберу',
        success: 'Тапсырыс қабылданды! Растауды күтіңіз.',
        error: 'Қате, қайта көріңіз.',
      },
    },
    faq: {
      title: 'Жиі Қойылатын Сұрақтар',
      subtitle: 'Донат сатып алу нұсқаулығы',
      backBtn: 'Артқа',
      instruction: 'Нұсқаулық',
      step1title: 'Донатты таңдаңыз',
      step1desc: 'Донаттар бөлімінде керекті пакетті таңдап, ақшаны банк картасына аударыңыз.',
      step2title: 'Чекті жіберіңіз',
      step2desc: 'Төлемнен кейін «Тапсырыс беру» батырмасын басып, ник, телефон нөмірін көрсетіп, чекті тіркеңіз.',
      step3title: 'Растауды күтіңіз',
      step3desc: 'Администратор тапсырысты тексеріп, донатты іске қосады. Жауап 1-24 сағат ішінде.',
      requisite: 'Банк реквизиттері:',
      faqListTitle: 'Жиі қойылатын сұрақтар',
      items: [
        {
          q: 'Серверге қалай қосылуға болады?',
          a: 'Minecraft ойынын ашып, Multiplayer бөліміне өтіп, mortymc.altyn.fun мекенжайымен серверді қосып, «Қосылу» батырмасын басыңыз.',
        },
        {
          q: 'Minecraft-тың қай нұсқасы қолдау көрсетеді?',
          a: 'Сервер Java Edition 1.20+ және Bedrock Edition нұсқаларын қолдайды. Соңғы нұсқаны қолдануды ұсынамыз.',
        },
        {
          q: 'Донат қаншалықты уақытта белсендіріледі?',
          a: 'Донат администратор растағаннан кейін 1-24 сағат ішінде белсендіріледі.',
        },
        {
          q: 'Ақшаны қайтарып ала аламын ба?',
          a: 'Донат белсендірілгеннен кейін ақша қайтарылмайды. Техникалық мәселелер туындаса, әкімшілікке хабарласыңыз.',
        },
      ],
    },
    admin: {
      title: 'Әкімші кірісі',
      placeholder: 'Кіру коды',
      submit: 'Кіру',
      error: 'Қате пароль',
      addDonate: '+ Донат қосу',
      donatesTab: 'Донаттар',
      viewReceipt: 'Чекті қарау',
      saved: 'Сақталды',
      orders: 'Тапсырыстар',
      editRequisite: 'Реквизиттер',
      logout: 'Шығу',
      noOrders: 'Тапсырыстар әлі жоқ',
      noDonates: 'Донаттар әлі қосылмаған',
      delete: 'Өшіру',
      donateForm: {
        title: 'Жаңа донат',
        name: 'Атауы',
        price: 'Бағасы (₸)',
        desc: 'Сипаттама',
        image: 'Сурет',
        save: 'Сақтау',
        cancel: 'Бас тарту',
      },
    },
    footer: {
      rights: '© 2026 MortyMC. Барлық құқықтар қорғалған.',
    },
  },

  EN: {
    langName: 'English',
    nav: {
      dashboard: 'Home',
      donates: 'Donations',
      faq: 'FAQ',
    },
    hero: {
      eyebrow: 'SERVER ONLINE',
      subtitle: 'NEXT GENERATION',
      desc: 'MortyMC is the best Minecraft server in Kazakhstan. New experience, new friends, new achievements.',
      join: 'Join Now',
      explore: 'Learn More',
      ip: 'Server IP:',
      copy: 'Copy',
    },
    about: {
      eyebrow: 'ABOUT US',
      title: 'THE MORTYMC',
      desc: 'MortyMC is not just a game, it\u2019s a community. On our server you\u2019ll find new friends, win epic battles, and build your own world.',
      btn1: 'Join Now',
      btn2: 'Donations',
    },
    gameplay: {
      title: 'PAGES',
    },
    stats: {
      players: 'Players',
      online: 'Online',
      worlds: 'Worlds',
      uptime: 'Uptime',
    },
    donates: {
      title: 'Donations',
      subtitle: 'Support the server and get exclusive perks',
      order: 'Order',
      backBtn: 'Back',
      empty: 'No donations added yet',
      sending: 'Sending...',
      modal: {
        title: 'Place an Order',
        nick: 'Minecraft nickname',
        phone: 'Phone number',
        file: 'Receipt / payment proof',
        fileBtn: 'Choose file',
        submit: 'Submit',
        success: 'Order received! Please wait for confirmation.',
        error: 'Error, please try again.',
      },
    },
    faq: {
      title: 'Frequently Asked Questions',
      subtitle: 'Guide to purchasing a donation',
      backBtn: 'Back',
      instruction: 'Instructions',
      step1title: 'Choose a donation',
      step1desc: 'In the donations section, pick the package you want and transfer the money to the bank card.',
      step2title: 'Send the receipt',
      step2desc: 'After payment, click "Order", enter your nickname, phone number, and attach the receipt.',
      step3title: 'Wait for confirmation',
      step3desc: 'The administrator will verify the order and activate the donation. Response within 1-24 hours.',
      requisite: 'Bank details:',
      faqListTitle: 'Frequently asked questions',
      items: [
        {
          q: 'How do I connect to the server?',
          a: 'Open Minecraft, go to the Multiplayer section, add the server with the address mortymc.altyn.fun, and click "Connect".',
        },
        {
          q: 'Which Minecraft version is supported?',
          a: 'The server supports Java Edition 1.20+ and Bedrock Edition. We recommend using the latest version.',
        },
        {
          q: 'How long does it take to activate a donation?',
          a: 'The donation is activated within 1-24 hours after administrator confirmation.',
        },
        {
          q: 'Can I get a refund?',
          a: 'Refunds are not available after a donation has been activated. If you have technical issues, please contact the administration.',
        },
      ],
    },
    admin: {
      title: 'Administrator Login',
      placeholder: 'Access code',
      submit: 'Log In',
      error: 'Incorrect password',
      addDonate: '+ Add Donation',
      donatesTab: 'Donations',
      viewReceipt: 'View receipt',
      saved: 'Saved',
      orders: 'Orders',
      editRequisite: 'Bank Details',
      logout: 'Log Out',
      noOrders: 'No orders yet',
      noDonates: 'No donations added yet',
      delete: 'Delete',
      donateForm: {
        title: 'New Donation',
        name: 'Name',
        price: 'Price (₸)',
        desc: 'Description',
        image: 'Image',
        save: 'Save',
        cancel: 'Cancel',
      },
    },
    footer: {
      rights: '© 2026 MortyMC. All rights reserved.',
    },
  },
};
